@startuml
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}

left to right direction

actor Recepcionista as RE
actor Paciente as PA
actor Medico as ME
actor Administrador as AD

rectangle "Gestion Hospitalaria" {

  ' -- Gestion de pacientes --
  usecase "Registrar paciente" as RP
  usecase "Registrar alergias" as RA
  usecase "Registrar contraindicaciones" as RC
  usecase "Consultar historial" as CH

  ' -- Gestion de citas --
  usecase "Agendar citas medicas" as AC
  usecase "Confirmar cita" as CEE
  usecase "Cancelar cita" as CC
  usecase "Atender cita" as AAC
  usecase "Completar cita" as CCC
  usecase "Registrar diagnosticos" as RD
  usecase "Registrar recetas medicas" as RCM

  ' -- Gestion de personal --
  usecase "Contratar empleados" as CE
  usecase "Asignar especialidades medicas" as AE
  usecase "Gestionar turnos de trabajo" as GT
  usecase "Asignar salarios base" as AS
}

RE --> RP
RE --> RA
RE --> RC
RE --> CH
RE --> AC
RE --> CEE

PA --> CH
PA --> CC

ME --> AAC
ME --> CCC
ME --> RD
ME --> RCM

AD --> CE
AD --> AE
AD --> GT
AD --> AS

RA .> RP : <<include>>
RC .> RP : <<include>>
CH .> RP : <<include>>
AC .> RP : <<include>>

CEE .> AC : <<include>>
AAC .> CEE : <<include>>
CCC .> AAC : <<include>>

RD .> CCC : <<include>>
RCM .> CCC : <<include>>

RCM .> RD : <<extend>>
CC .> AC : <<extend>>

AE .> CE : <<include>>
GT .> CE : <<include>>
AS .> CE : <<include>>
@enduml