@startuml
enum GrupoSanguineo {
A_POSITIVO
A_NEGATIVO
B_POSITIVO
B_NEGATIVO
AB_POSITIVO
AB_NEGATIVO
O_POSITIVO
O_NEGATIVO
}

enum Especialidad {
ENFERMERO
CIRUJANO
}

enum estadoCita {
EN_ESPERA
CONFIRMADA
EN_ATENCION
COMPLETADA
CANCELADA
}

abstract class  Persona {
-id: String
-nombre: String
-apellido: String
-fechaNacimiento: LocalDate
-email: String

+{abstract} calcularEdad(): int
+{abstract} obtenerTipo(): String
}

abstract class Empleado {
-legajo: String
-fechaContratacion: LocalDate
-salarioBase: int
-activo: boolean

+{abstract} calcularSalario(): double
+antiguedad(): int
}

class Paciente {
-historiaClinicaId: String
-grupoSanguineo: GrupoSanguineo
-alergias: List<String>
-citas: List<CitaMedica>

+agregarAlergia(): void
+obtenerHistorial(): void
}

class Medico {
-numeroLicencia: int
-especialidad: Especialidad
-pacientesAsignados: List<Paciente>
-citasAtendidas: int

+atenderPaciente(): void
+calcularSalario(): double
}

class Cirujano {
-cirugiasRealizadas: int
-disponibleEmergencias: boolean

+realizarCirugia: void
+calcularBono: void
}

class Enfermero {
-turno
}
@enduml
